# Generated by Django 5.1.7 on 2026-03-01 19:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='payment',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='paymentplan',
            options={'ordering': ['price']},
        ),
        migrations.AlterField(
            model_name='payment',
            name='payment_method',
            field=models.CharField(choices=[('mpesa', 'M-Pesa'), ('card', 'Card'), ('bank', 'Bank Transfer')], default='mpesa', max_length=20),
        ),
        migrations.AlterField(
            model_name='payment',
            name='plan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='payments.paymentplan'),
        ),
        migrations.AlterField(
            model_name='paymentplan',
            name='duration_days',
            field=models.PositiveIntegerField(default=30),
        ),
        migrations.AlterField(
            model_name='paymentplan',
            name='plan_type',
            field=models.CharField(choices=[('job_boost', 'Job Boost'), ('profile_highlight', 'Profile Highlight'), ('featured_listing', 'Featured Listing'), ('verification', 'Account Verification')], max_length=50),
        ),
    ]
