# Generated by Django 5.1.7 on 2026-04-17 13:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0005_payment_balance_due_payment_is_installment'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='is_mpesa_stk',
            field=models.BooleanField(default=False, help_text='Payment via M-Pesa STK push'),
        ),
        migrations.AddField(
            model_name='payment',
            name='mpesa_transaction_id',
            field=models.CharField(blank=True, help_text='M-Pesa MpesaReceiptNumber from callback', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='payment_verified_at',
            field=models.DateTimeField(blank=True, help_text='When M-Pesa confirmed success', null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='stk_initiated_at',
            field=models.DateTimeField(blank=True, help_text='When STK push was triggered', null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='stk_reference_id',
            field=models.CharField(blank=True, help_text='M-Pesa CheckoutRequestID', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='paymentplan',
            name='plan_type',
            field=models.CharField(choices=[('job_boost', 'Job Boost'), ('profile_highlight', 'Profile Highlight'), ('featured_listing', 'Featured Listing'), ('verification', 'Account Verification'), ('academy_bundle', 'Academy Triple Bundle'), ('course_payment', 'Individual Course Payment')], max_length=50),
        ),
        migrations.CreateModel(
            name='UserSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('active', 'Active'), ('expired', 'Expired'), ('cancelled', 'Cancelled')], default='active', max_length=20)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(help_text='When subscription expires')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='subscriptions', to='payments.paymentplan')),
                ('user', models.ForeignKey(limit_choices_to={'user_type': 'employer'}, on_delete=django.db.models.deletion.CASCADE, related_name='subscriptions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'User Subscriptions',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MonthlyContribution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveIntegerField(help_text='e.g. 2026')),
                ('month', models.PositiveIntegerField(help_text='1-12')),
                ('calculated_salary', models.DecimalField(decimal_places=2, default=0.0, help_text='Sum of completed job salaries for the month', max_digits=10)),
                ('amount_due', models.DecimalField(decimal_places=2, default=0.0, help_text='3% of calculated_salary', max_digits=10)),
                ('payment_status', models.CharField(choices=[('pending', 'Pending'), ('paid', 'Paid'), ('ignored', 'Ignored')], default='pending', max_length=20)),
                ('payment_date', models.DateTimeField(blank=True, help_text='When payment was made', null=True)),
                ('mpesa_transaction_id', models.CharField(blank=True, help_text='M-Pesa receipt number', max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('worker', models.ForeignKey(limit_choices_to={'user_type': 'househelp'}, on_delete=django.db.models.deletion.CASCADE, related_name='monthly_contributions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Monthly Contributions',
                'ordering': ['-year', '-month'],
                'unique_together': {('worker', 'year', 'month')},
            },
        ),
    ]
