# Generated by Django 5.1.7 on 2026-04-17 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0007_payment_contribution'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentplan',
            name='can_use_video',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='paymentplan',
            name='chat_conversation_limit',
            field=models.PositiveIntegerField(default=0, help_text='0 for unlimited'),
        ),
        migrations.AddField(
            model_name='paymentplan',
            name='chat_message_limit',
            field=models.PositiveIntegerField(default=0, help_text='0 for unlimited'),
        ),
        migrations.AddField(
            model_name='paymentplan',
            name='job_posting_fee',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='paymentplan',
            name='video_call_limit_mins',
            field=models.PositiveIntegerField(default=0, help_text='0 for unlimited'),
        ),
    ]
