# Generated by Django 5.1.7 on 2026-04-17 20:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0006_alter_job_is_active'),
        ('payments', '0008_paymentplan_can_use_video_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='job',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments', to='jobs.job'),
        ),
    ]
