# Generated by Django 5.1.7 on 2026-04-19 11:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_add_unique_constraints'),
        ('payments', '0009_payment_job'),
    ]

    operations = [
    ]
