# Generated by Django 5.1.7 on 2025-03-29 00:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='application',
            options={},
        ),
        migrations.AlterUniqueTogether(
            name='application',
            unique_together=set(),
        ),
    ]
