# Generated by Django 5.1.7 on 2026-03-09 01:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0004_alter_application_applicant'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='city',
            field=models.CharField(blank=True, choices=[('nairobi', 'Nairobi'), ('mombasa', 'Mombasa'), ('kisumu', 'Kisumu'), ('nakuru', 'Nakuru'), ('eldoret', 'Eldoret'), ('thika', 'Thika'), ('machakos', 'Machakos'), ('nyeri', 'Nyeri'), ('meru', 'Meru'), ('kakamega', 'Kakamega'), ('kisii', 'Kisii'), ('garissa', 'Garissa'), ('embu', 'Embu'), ('nyahururu', 'Nyahururu'), ('kitale', 'Kitale'), ('naivasha', 'Naivasha'), ('malindi', 'Malindi'), ('luanda', 'Luanda'), ('bungoma', 'Bungoma'), ('lodwar', 'Lodwar'), ('lamu', 'Lamu'), ('narok', 'Narok'), ('voi', 'Voi'), ('nanyuki', 'Nanyuki'), ('karatina', 'Karatina'), ('ruiru', 'Ruiru'), ('ongata_rongai', 'Ongata Rongai'), ('syokimau', 'Syokimau'), ('kikuyu', 'Kikuyu'), ('ruaka', 'Ruaka')], max_length=50),
        ),
    ]
