# Generated by Django 5.1.7 on 2026-04-21 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0006_alter_job_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='requirements_met',
            field=models.JSONField(blank=True, default=list, help_text='List of requirements the applicant satisfies'),
        ),
    ]
