services:
  - type: web
    name: housekeeper-connect
    env: python
    buildCommand: "./build.sh"
    startCommand: "python manage.py migrate --noinput && gunicorn housekeeper_connect.wsgi:application"
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: 4
      - key: DATABASE_URL
        sync: false
