# Generated by Django 5.1.7 on 2026-03-09 00:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_add_skills_experience'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='badge_childcare',
            field=models.BooleanField(default=False, verbose_name='Childcare Certified'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='badge_cleaning',
            field=models.BooleanField(default=False, verbose_name='Cleaning Certified'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='badge_elder_care',
            field=models.BooleanField(default=False, verbose_name='Elder Care Certified'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='badge_kitchen',
            field=models.BooleanField(default=False, verbose_name='Kitchen Certified'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='badge_verified_id',
            field=models.BooleanField(default=False, verbose_name='Verified ID'),
        ),
    ]
