# Generated by Django 5.1.7 on 2026-03-09 00:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_customuser_badge_childcare_customuser_badge_cleaning_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='police_clearance',
        ),
        migrations.AddField(
            model_name='customuser',
            name='badge_professional_standards',
            field=models.BooleanField(default=False, verbose_name='Professional Standards Certified'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='last_reminder_sent',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
