# Generated by Django 5.1.7 on 2026-03-12 01:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_remove_customuser_police_clearance_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='police_clearance',
            field=models.FileField(blank=True, help_text='Police Clearance Certificate / Good Conduct', null=True, upload_to='worker_docs/%Y/%m/%d/'),
        ),
    ]
