# Generated by Django 5.1.7 on 2026-04-17 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_customuser_badge_appliance'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='is_paid_verified',
            field=models.BooleanField(default=False, help_text='User paid 250 KES for annual verification', verbose_name='Paid Verified Member'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='paid_verification_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Verification Payment Date'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='paid_verification_expires_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Verification Expiry Date'),
        ),
    ]
