# Generated by Hand on 2026-04-17 15:24
from django.db import migrations

def fix_empty_usernames(apps, schema_editor):
    CustomUser = apps.get_model('accounts', 'CustomUser')
    # Find users with empty username
    for user in CustomUser.objects.filter(username=''):
        # Set username to phone_number (which is our platform standard)
        if user.phone_number:
            user.username = user.phone_number
            user.save()
        else:
            # Fallback for extreme cases (missing phone)
            user.username = f"user_{user.id}"
            user.save()

def reverse_fix(apps, schema_editor):
    pass

class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_customuser_is_paid_verified_and_more'),
    ]

    operations = [
        migrations.RunPython(fix_empty_usernames, reverse_fix),
    ]
