# Generated by Django 5.1.7 on 2026-04-17 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_fix_empty_usernames'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlatformDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('doc_type', models.CharField(choices=[('worker_agreement', 'Worker Agreement Template'), ('employer_agreement', 'Employer Agreement Template'), ('code_of_conduct', 'Code of Conduct'), ('other', 'Other')], help_text='Only one active document of each type is allowed.', max_length=30, unique=True)),
                ('document_file', models.FileField(upload_to='platform_docs/')),
                ('description', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Platform Document',
                'verbose_name_plural': 'Platform Documents',
            },
        ),
    ]
