# Generated by Django 5.1.7 on 2026-04-17 23:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_platformdocument'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='didit_session_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='didit_verification_status',
            field=models.CharField(choices=[('none', 'None'), ('pending', 'Pending'), ('completed', 'Completed'), ('failed', 'Failed')], default='none', max_length=50),
        ),
    ]
