# Generated by Django 5.1.7 on 2026-04-19 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_customuser_has_completed_first_verification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='has_completed_first_verification',
            field=models.BooleanField(default=False, help_text='Track if worker completed first-time Didit verification'),
        ),
    ]
