# Generated by Django 5.1.7 on 2026-04-21 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_alter_customuser_has_completed_first_verification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='didit_verification_status',
            field=models.CharField(choices=[('none', 'None'), ('pending', 'Pending'), ('completed', 'Completed'), ('failed', 'Failed'), ('approved', 'Approved'), ('declined', 'Declined'), ('expired', 'Expired'), ('in_review', 'In Review')], default='none', max_length=50),
        ),
    ]
