# Generated by Django 5.1.7 (hand-written merge, equivalent of `makemigrations --merge`)

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_customuser_is_premium_premium_until_notification_preferences'),
        ('accounts', '0016_alter_customuser_didit_verification_status'),
    ]

    operations = [
    ]
