# Generated by Django 5.1.7 on 2026-03-12 01:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_question_is_final_exam_question_lesson_quizattempt_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursecompletion',
            name='certificate',
            field=models.FileField(blank=True, null=True, upload_to='certificates/%Y/%m/'),
        ),
    ]
